# -*- coding: utf-8 -*-
"""Essay1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1euZX32a8T_pHaGyh6u-JzZ1i8H_g6NEG
"""

import requests

url = "https://berita-indo-api-next.vercel.app/api/cnn-news/teknologi"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()

print(data.get('message'))

print("Total data:", data.get('total'))

for news in data.get('data'):
        print("Title:", news.get('title'))
        print("Link:", news.get('link'))
        print("Content Snippet:", news.get('contentSnippet'))
        print("isoDate:", news.get('isoDate'))
        print("Small Image:", news.get('image').get('small'))
        print("Large Image:", news.get('image').get('large'))
        print("\n")  # Garis baru untuk pemisah
else:
    print("Failed to retrieve data from the API")

import requests
import pandas as pd

url = "https://berita-indo-api-next.vercel.app/api/cnn-news/teknologi"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()

df = pd.DataFrame(data['data'])

df['isoDate'] = pd.to_datetime(df['isoDate'])

print(df.columns)

print(df.isoDate)

aggregated_data = df.groupby('title').size().reset_index(name='Total News').sort_values(by='Total News', ascending=False)
print(aggregated_data)